### ISSUE TITLE
Build fails on AmberTools20 package

### ISSUE THREAD

**Issue by j-wags** [openforcefield/toolkit-installer-constructor#3]
I was rebuilding the installers for the openforcefields 1.2.0 release, and ran into this issue. This will be blocking for the 0.7.0 release. Might be able to kludge something into the build system to work around this. 

`python run.py`
```
platform: osx-64
conda packages download: /Users/jeffreywagner/.conda/constructor/osx-64
specs: ['conda', 'notebook', 'requests', 'openforcefield', 'smirnoff99Frosst', 'python 3.6*', 'pytest', 'python']
Collecting package metadata (repodata.json): done
Solving environment: done

name: openforcefield
version: 0.6.0
cache download location: /Users/jeffreywagner/.conda/constructor/osx-64
platform: osx-64
number of package: 156
    python-3.6.10-h4334963_1011_cpython.tar.bz2 (latest: defaults/osx-64::python==3.8.3=h26836e1_1)
    bzip2-1.0.8-h0b31af3_2.tar.bz2
    ca-certificates-2020.4.5.1-hecc5488_0.tar.bz2
    fftw3f-3.3.4-2.tar.bz2
    jpeg-9d-h0b31af3_0.tar.bz2
    libcxx-10.0.0-h1af66ff_2.tar.bz2
    libiconv-1.15-h0b31af3_1006.tar.bz2 (latest: defaults/osx-64::libiconv==1.16=h1de35cc_0)
    libsodium-1.0.17-h01d97ff_0.tar.bz2 (latest: conda-forge/osx-64::libsodium==1.0.18=h01d97ff_0)
    libwebp-base-1.1.0-h0b31af3_3.tar.bz2
    llvm-openmp-10.0.0-h28b9765_0.tar.bz2
    pandoc-2.9.2.1-0.tar.bz2
    perl-5.26.2-haec8ef5_1006.tar.bz2
    pixman-0.38.0-h01d97ff_1003.tar.bz2
    pthread-stubs-0.4-h1de35cc_1001.tar.bz2
    xorg-kbproto-1.0.7-h1de35cc_1002.tar.bz2
    xorg-libice-1.0.10-h01d97ff_0.tar.bz2
    xorg-libxau-1.0.9-h1de35cc_0.tar.bz2
    xorg-libxdmcp-1.1.3-h01d97ff_0.tar.bz2
    xorg-xextproto-7.3.0-h1de35cc_1002.tar.bz2
    xorg-xproto-7.0.31-h1de35cc_1007.tar.bz2
    xz-5.2.5-h0b31af3_0.tar.bz2
    yaml-0.2.4-h0b31af3_0.tar.bz2
    zlib-1.2.11-h0b31af3_1006.tar.bz2
    hdf4-4.2.13-h84186c3_1003.tar.bz2
    icu-67.1-h4a8c4bd_0.tar.bz2
    libffi-3.2.1-h4a8c4bd_1007.tar.bz2 (latest: defaults/osx-64::libffi==3.3=h0a44026_1)
    libgfortran-4.0.0-2.tar.bz2
    libpng-1.6.37-hbbe82c9_1.tar.bz2
    libxcb-1.13-h1de35cc_1002.tar.bz2
    lz4-c-1.9.2-h4a8c4bd_1.tar.bz2
    ncurses-6.1-h0a44026_1002.tar.bz2 (latest: defaults/osx-64::ncurses==6.2=h0a44026_1)
    openssl-1.1.1g-h0b31af3_0.tar.bz2
    pcre-8.44-h4a8c4bd_0.tar.bz2
    tk-8.6.10-hbbe82c9_0.tar.bz2
    xorg-libsm-1.2.3-h01d97ff_1000.tar.bz2
    zeromq-4.3.2-h6de7cb9_2.tar.bz2
    fftw-3.3.8-nompi_h44ae4c8_1110.tar.bz2
    freetype-2.10.2-h8da9a1a_0.tar.bz2
    gettext-0.19.8.1-h46ab8bc_1002.tar.bz2
    hdf5-1.10.6-nompi_h3e39495_100.tar.bz2
    libedit-3.1.20170329-hcfe32e1_1001.tar.bz2 (latest: defaults/osx-64::libedit==3.1.20181209=hb402a30_0)
    libopenblas-0.3.9-h3d69b6c_0.tar.bz2
    libssh2-1.9.0-h39bdce6_2.tar.bz2
    libxml2-2.9.10-hc06c4ae_1.tar.bz2
    readline-8.0-hcfe32e1_0.tar.bz2
    xorg-libx11-1.6.9-h0b31af3_0.tar.bz2
    zstd-1.4.4-h4b3e974_3.tar.bz2
    boost-cpp-1.72.0-hef959ae_1.tar.bz2 (latest: conda-forge/osx-64::boost-cpp==1.73.0=hef959ae_1)
    fontconfig-2.13.1-h79c0d67_1002.tar.bz2
    krb5-1.17.1-h1752a42_0.tar.bz2
    libblas-3.8.0-16_openblas.tar.bz2
    libtiff-4.1.0-h2ae36a8_6.tar.bz2
    sqlite-3.30.1-h93121df_0.tar.bz2 (latest: defaults/osx-64::sqlite==3.31.1=h5c1f38d_1)
    xorg-libxext-1.3.4-h01d97ff_0.tar.bz2
    xorg-libxt-1.2.0-h01d97ff_0.tar.bz2
    libcblas-3.8.0-16_openblas.tar.bz2
    libcurl-7.69.1-hc0b9707_0.tar.bz2
    liblapack-3.8.0-16_openblas.tar.bz2
    arpack-3.7.0-hbb27dc6_1.tar.bz2
    attrs-19.3.0-py_0.tar.bz2
    backcall-0.1.0-py_0.tar.bz2
    curl-7.69.1-h2d98d24_0.tar.bz2
    decorator-4.4.2-py_0.tar.bz2
    defusedxml-0.6.0-py_0.tar.bz2
    glib-2.64.3-h577aef8_0.tar.bz2
    idna-2.9-py_1.tar.bz2
    ipython_genutils-0.2.0-py_1.tar.bz2
    more-itertools-8.3.0-py_0.tar.bz2
    olefile-0.46-py_0.tar.bz2
    pandocfilters-1.4.2-py_1.tar.bz2
    parso-0.7.0-pyh9f0ad1d_0.tar.bz2
    prometheus_client-0.8.0-pyh9f0ad1d_0.tar.bz2
    ptyprocess-0.6.0-py_1001.tar.bz2
    py-1.8.1-py_0.tar.bz2
    pycparser-2.20-py_0.tar.bz2
    pyparsing-2.4.7-pyh9f0ad1d_0.tar.bz2
    python_abi-3.6-1_cp36m.tar.bz2 (latest: conda-forge/osx-64::python_abi==3.8=1_cp38)
    pytz-2020.1-pyh9f0ad1d_0.tar.bz2
    send2trash-1.5.0-py_0.tar.bz2
    six-1.15.0-pyh9f0ad1d_0.tar.bz2
    testpath-0.4.4-py_0.tar.bz2
    toml-0.10.1-pyh9f0ad1d_0.tar.bz2
    tqdm-4.46.0-pyh9f0ad1d_0.tar.bz2
    wcwidth-0.2.2-pyh9f0ad1d_0.tar.bz2
    webencodings-0.5.1-py_1.tar.bz2
    xmltodict-0.12.0-py_0.tar.bz2
    zipp-3.1.0-py_0.tar.bz2
    appnope-0.1.0-py36h9f0ad1d_1001.tar.bz2
    cairo-1.16.0-ha8983da_1004.tar.bz2
    certifi-2020.4.5.1-py36h9f0ad1d_0.tar.bz2
    cffi-1.14.0-py36h356ff06_0.tar.bz2 (latest: conda-forge/noarch::cffi==1.14.0=2_pypy)
    chardet-3.0.4-py36h9f0ad1d_1006.tar.bz2
    conda-package-handling-1.6.0-py36h37b9a7d_2.tar.bz2 (latest: defaults/osx-64::conda-package-handling==1.6.1=py36h1de35cc_0)
    cycler-0.10.0-py_2.tar.bz2
    cython-0.29.19-py36h0130604_0.tar.bz2
    entrypoints-0.3-py36h9f0ad1d_1001.tar.bz2
    importlib-metadata-1.6.0-py36h9f0ad1d_0.tar.bz2
    jedi-0.17.0-py36h9f0ad1d_0.tar.bz2
    kiwisolver-1.2.0-py36h863e41a_0.tar.bz2
    libnetcdf-4.7.4-nompi_ha11d67f_104.tar.bz2
    markupsafe-1.1.1-py36h37b9a7d_1.tar.bz2
    mistune-0.8.4-py36h37b9a7d_1001.tar.bz2
    msgpack-python-1.0.0-py36h863e41a_1.tar.bz2
    numpy-1.18.4-py36hdc5ca10_0.tar.bz2
    packaging-20.4-pyh9f0ad1d_0.tar.bz2
    pexpect-4.8.0-py36h9f0ad1d_1.tar.bz2
    pickleshare-0.7.5-py36h9f0ad1d_1001.tar.bz2
    pillow-7.1.2-py36h2ae5dfa_0.tar.bz2
    pycosat-0.6.3-py36h37b9a7d_1004.tar.bz2
    pyrsistent-0.16.0-py36h37b9a7d_0.tar.bz2
    pysocks-1.7.1-py36h9f0ad1d_1.tar.bz2
    python-dateutil-2.8.1-py_0.tar.bz2
    pyyaml-5.3.1-py36h37b9a7d_0.tar.bz2
    pyzmq-19.0.1-py36h820b253_0.tar.bz2
    ruamel_yaml-0.15.80-py36h37b9a7d_1001.tar.bz2 (latest: defaults/osx-64::ruamel_yaml==0.15.87=py27h1de35cc_0)
    tornado-6.0.4-py36h37b9a7d_1.tar.bz2
    traitlets-4.3.3-py36h9f0ad1d_1.tar.bz2
    boost-1.72.0-py36hbf1eeb5_0.tar.bz2 (latest: conda-forge/osx-64::boost==1.73.0=py38hd74bcbf_0)
    brotlipy-0.7.0-py36h37b9a7d_1000.tar.bz2
    bson-0.5.9-py_0.tar.bz2
    cryptography-2.9.2-py36hc9d8292_0.tar.bz2
    importlib_metadata-1.6.0-0.tar.bz2
    jupyter_core-4.6.3-py36h9f0ad1d_1.tar.bz2
    netcdf-fortran-4.5.2-nompi_hcfc364a_106.tar.bz2
    openmm-7.4.2-py36_cuda101_rc_1.tar.bz2
    pandas-1.0.4-py36hcc1bba6_0.tar.bz2
    pycairo-1.19.1-py36h1ef2672_3.tar.bz2
    scipy-1.4.1-py36h1dac7e4_3.tar.bz2
    setuptools-47.1.1-py36h9f0ad1d_0.tar.bz2
    terminado-0.8.3-py36h9f0ad1d_1.tar.bz2
    bleach-3.1.5-pyh9f0ad1d_0.tar.bz2
    jinja2-2.11.2-pyh9f0ad1d_0.tar.bz2
    jsonschema-3.2.0-py36h9f0ad1d_1.tar.bz2
    jupyter_client-6.1.3-py_0.tar.bz2
    matplotlib-base-3.2.1-py36h83d3ec1_0.tar.bz2
    networkx-2.4-py_1.tar.bz2
    openforcefields-1.2.0-py36_0.tar.bz2
    pluggy-0.13.1-py36h9f0ad1d_1.tar.bz2
    pygments-2.6.1-py_0.tar.bz2
    pyopenssl-19.1.0-py_1.tar.bz2
    rdkit-2020.03.2-py36h8e01224_0.tar.bz2
    smirnoff99frosst-1.1.0-py36_1.tar.bz2
    wheel-0.34.2-py_1.tar.bz2
    ambertools-20.0-py36h95059d0_2.tar.bz2
    nbformat-5.0.6-py_0.tar.bz2
    pip-20.1.1-py_1.tar.bz2
    prompt-toolkit-3.0.5-py_0.tar.bz2
    pytest-5.4.2-py36h9f0ad1d_0.tar.bz2
    urllib3-1.25.9-py_0.tar.bz2
    ipython-7.15.0-py36h9f0ad1d_0.tar.bz2
    nbconvert-5.6.1-py36h9f0ad1d_1.tar.bz2
    requests-2.23.0-pyh8c360ce_2.tar.bz2
    conda-4.8.3-py36h9f0ad1d_1.tar.bz2 (latest: conda-forge/osx-64::conda==4.8.3=py38h32f6830_2)
    ipykernel-5.3.0-py36h95af2a2_0.tar.bz2
    notebook-6.0.3-py36h9f0ad1d_0.tar.bz2
    openforcefield-0.6.0-py36_1.tar.bz2

fetching: python-3.6.10-h4334963_1011_cpython.tar.bz2
fetching: python_abi-3.6-1_cp36m.tar.bz2
fetching: appnope-0.1.0-py36h9f0ad1d_1001.tar.bz2
fetching: certifi-2020.4.5.1-py36h9f0ad1d_0.tar.bz2
fetching: cffi-1.14.0-py36h356ff06_0.tar.bz2
fetching: chardet-3.0.4-py36h9f0ad1d_1006.tar.bz2
fetching: conda-package-handling-1.6.0-py36h37b9a7d_2.tar.bz2
fetching: cython-0.29.19-py36h0130604_0.tar.bz2
fetching: entrypoints-0.3-py36h9f0ad1d_1001.tar.bz2
fetching: importlib-metadata-1.6.0-py36h9f0ad1d_0.tar.bz2
fetching: jedi-0.17.0-py36h9f0ad1d_0.tar.bz2
fetching: kiwisolver-1.2.0-py36h863e41a_0.tar.bz2
fetching: markupsafe-1.1.1-py36h37b9a7d_1.tar.bz2
fetching: mistune-0.8.4-py36h37b9a7d_1001.tar.bz2
fetching: msgpack-python-1.0.0-py36h863e41a_1.tar.bz2
fetching: numpy-1.18.4-py36hdc5ca10_0.tar.bz2
fetching: pexpect-4.8.0-py36h9f0ad1d_1.tar.bz2
fetching: pickleshare-0.7.5-py36h9f0ad1d_1001.tar.bz2
fetching: pillow-7.1.2-py36h2ae5dfa_0.tar.bz2
fetching: pycosat-0.6.3-py36h37b9a7d_1004.tar.bz2
fetching: pyrsistent-0.16.0-py36h37b9a7d_0.tar.bz2
fetching: pysocks-1.7.1-py36h9f0ad1d_1.tar.bz2
fetching: pyyaml-5.3.1-py36h37b9a7d_0.tar.bz2
fetching: pyzmq-19.0.1-py36h820b253_0.tar.bz2
fetching: ruamel_yaml-0.15.80-py36h37b9a7d_1001.tar.bz2
fetching: tornado-6.0.4-py36h37b9a7d_1.tar.bz2
fetching: traitlets-4.3.3-py36h9f0ad1d_1.tar.bz2
fetching: boost-1.72.0-py36hbf1eeb5_0.tar.bz2
fetching: brotlipy-0.7.0-py36h37b9a7d_1000.tar.bz2
fetching: cryptography-2.9.2-py36hc9d8292_0.tar.bz2
fetching: jupyter_core-4.6.3-py36h9f0ad1d_1.tar.bz2
fetching: openmm-7.4.2-py36_cuda101_rc_1.tar.bz2
fetching: pandas-1.0.4-py36hcc1bba6_0.tar.bz2
fetching: pycairo-1.19.1-py36h1ef2672_3.tar.bz2
fetching: scipy-1.4.1-py36h1dac7e4_3.tar.bz2
fetching: setuptools-47.1.1-py36h9f0ad1d_0.tar.bz2
fetching: terminado-0.8.3-py36h9f0ad1d_1.tar.bz2
fetching: jsonschema-3.2.0-py36h9f0ad1d_1.tar.bz2
fetching: matplotlib-base-3.2.1-py36h83d3ec1_0.tar.bz2
fetching: openforcefields-1.2.0-py36_0.tar.bz2
fetching: pluggy-0.13.1-py36h9f0ad1d_1.tar.bz2
fetching: rdkit-2020.03.2-py36h8e01224_0.tar.bz2
fetching: smirnoff99frosst-1.1.0-py36_1.tar.bz2
fetching: ambertools-20.0-py36h95059d0_2.tar.bz2
fetching: pytest-5.4.2-py36h9f0ad1d_0.tar.bz2
fetching: ipython-7.15.0-py36h9f0ad1d_0.tar.bz2
fetching: nbconvert-5.6.1-py36h9f0ad1d_1.tar.bz2
fetching: conda-4.8.3-py36h9f0ad1d_1.tar.bz2
fetching: ipykernel-5.3.0-py36h95af2a2_0.tar.bz2
fetching: notebook-6.0.3-py36h9f0ad1d_0.tar.bz2
fetching: openforcefield-0.6.0-py36_1.tar.bz2
Checking for duplicate files ...
Traceback (most recent call last):
  File "/Users/jeffreywagner/miniconda3/envs/cookiecutter/bin/constructor", line 11, in <module>
    sys.exit(main())
  File "/Users/jeffreywagner/miniconda3/envs/cookiecutter/lib/python3.7/site-packages/constructor/main.py", line 244, in main
    dry_run=args.dry_run, conda_exe=args.conda_exe)
  File "/Users/jeffreywagner/miniconda3/envs/cookiecutter/lib/python3.7/site-packages/constructor/main.py", line 119, in main_build
    fcp_main(info, verbose=verbose, dry_run=dry_run)
  File "/Users/jeffreywagner/miniconda3/envs/cookiecutter/lib/python3.7/site-packages/constructor/fcp.py", line 262, in main
    ignore_duplicate_files, verbose, dry_run
  File "/Users/jeffreywagner/miniconda3/envs/cookiecutter/lib/python3.7/site-packages/constructor/fcp.py", line 232, in _main
    pc_recs, platform, ignore_duplicate_files
  File "/Users/jeffreywagner/miniconda3/envs/cookiecutter/lib/python3.7/site-packages/constructor/fcp.py", line 142, in check_duplicates_files
    getsize(join(extracted_package_dir, short_path)))
  File "/Users/jeffreywagner/miniconda3/envs/cookiecutter/lib/python3.7/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jeffreywagner/.conda/constructor/osx-64/ambertools-20.0-py36h95059d0_2/dat/leap/cmd/leaprc.protein.ff12pol'
```

**Comment by j-wags** [comment]
From @jaimergp:

> That ghost file again >_< It's a broken symlink that I thought they had fixed in AT20 because conda build wasn't complaining about it so I removed the patch. https://github.com/conda-forge/ambertools-feedstock/blob/d6d71db3ebdd91690ae9f487cd4c5264483e71cb/recipe/patches/do_not_symlink_missing_ff12pol.patch
> 
> recipe/patches/do_not_symlink_missing_ff12pol.patch
> diff --git a/dat/CMakeLists.txt b/dat/CMakeLists.txt
> index ecfc5514..a822db5b 100644
> --- a/dat/CMakeLists.txt
> +++ b/dat/CMakeLists.txt
> @@ -3,6 +3,6 @@
>  
>  install(DIRECTORY . USE_SOURCE_PERMISSIONS DESTINATION ${DATADIR} COMPONENT Data)
>  
> -if(NOT (HOST_WINDOWS OR TARGET_WINDOWS))
> -    installtime_create_symlink(${CMAKE_INSTALL_POSTFIX}dat/leap/cmd/leaprc.protein.ff12polL ${CMAKE_INSTALL_POSTFIX}dat/leap/cmd/leaprc.protein.ff12pol Data)
> -endif()
> +# if(NOT (HOST_WINDOWS OR TARGET_WINDOWS))
> +#     installtime_create_symlink(${CMAKE_INSTALL_POSTFIX}dat/leap/cmd/leaprc.protein.ff12polL ${CMAKE_INSTALL_POSTFIX}dat/leap/cmd/leaprc.protein.ff12pol Data)
> +# endif()
> 
> Show less
> <https://github.com/conda-forge/ambertools-feedstock|conda-forge/ambertools-feedstock>conda-forge/ambertools-feedstock | Added by GitHub
> 00:53
> you can try to fix the error by providing the file again (it should be a copy of *ff12polL (edited) 
> 00:53
> also, I noticed there's a mixture of defaults and conda-forge in key packages
> 00:53
> that's a fragile setting and might create ABI conflicts down the line
> 00:54
> does conda-forge have priority over defaults? are you using strict channel priority? otherwise the above happens

**Comment by mattwthompson** [comment]
Closing as likely stale.
